#!/bin/zsh

set +e

cd "$( dirname "${BASH_SOURCE[0]}" )"

lang=${1:?language parameter is unset}
today=$(date +%d)
day=${2-$today}
input=input/day$day.txt

if [ -e ".venv" ]; then
    source ./.venv/bin/activate
else
    echo "No virtual environment found at '.venv'. Creating …"
    python -m venv .venv
    source ./.venv/bin/activate
    pip install -U advent-of-code-data
fi

if [ -e "$input" ]; then
    echo "$input already exists"
elif command -v aocd >/dev/null; then
    mkdir -pv input
    # fetch the puzzle input via https://github.com/wimglenn/advent-of-code-data
    aocd $day > "$input"
    # add trailing newline if necessary
    sed -i -e '$a\' "$input"
    echo "$input created"
else
    echo "aocd not found; skipping input file creation"
fi

case "$lang" in
    rust)
        ./setup_day_rust;;
    haskell)
        ./setup_day_haskell;;
    *)
        exit;;
esac
