[package]
name = "day-04"
version = "0.1.0"
authors = ["FichteFoll <fichtefoll2@googlemail.com>"]
edition = "2018"

[dependencies]
regex = "1.1"
chrono = "0.4"
error-chain = "0.12"
lazy_static = "1.2"
